#!/usr/bin/env bash
# Resolve the build identity and write the files that depend on it. Every build
# path runs this first (install.sh, build-release.sh, CI).
#
# Why generated: the Apple team id, bundle prefix and App Group name are yours,
# not the project's, and they have to agree in four places — project.yml, both
# .entitlements files, and Swift. Generating them from one source keeps them in
# step and keeps them out of the repo.
#
# Values come from, in order of precedence:
#   1. the environment
#   2. local-config/build.env   (gitignored — this machine's real values)
#   3. build.env.example        (committed placeholders, so a clone still builds)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

envval() { grep "^$1=" "$2" 2>/dev/null | head -1 | cut -d= -f2-; }

for key in BUNDLE_PREFIX APP_NAME DEVELOPMENT_TEAM; do
    if [ -z "${!key:-}" ]; then
        v="$(envval "$key" local-config/build.env)"
        [ -z "$v" ] && v="$(envval "$key" build.env.example)"
        export "$key=$v"
    fi
done
: "${BUNDLE_PREFIX:?missing — see build.env.example}"
: "${APP_NAME:?missing — see build.env.example}"
: "${DEVELOPMENT_TEAM:?missing — see build.env.example}"

# App Group naming differs by platform and both forms are mandatory:
#   macOS — must carry the Team ID prefix, or a sandboxed app can't open the
#           container it shares with its widget.
#   iOS   — must begin with "group.", and must NOT carry the team prefix.
# Getting this wrong fails at runtime (nil container URL), not at build time.
export APP_GROUP="${APP_GROUP:-$DEVELOPMENT_TEAM.group.$BUNDLE_PREFIX.$APP_NAME}"
export APP_GROUP_IOS="${APP_GROUP_IOS:-group.$BUNDLE_PREFIX.$APP_NAME}"
export BUNDLE_ID="${BUNDLE_ID:-$BUNDLE_PREFIX.$APP_NAME}"

echo "==> team $DEVELOPMENT_TEAM · bundle $BUNDLE_ID"
echo "    groups: macOS $APP_GROUP · iOS $APP_GROUP_IOS"

# ── Swift: one constant every target reads ───────────────────────────────────
cat > Shared/BuildConfig.generated.swift <<SWIFT
// Generated by scripts/configure.sh — do not edit, do not commit.
import Foundation

enum BuildConfig {
    #if os(macOS)
    static let appGroup = "$APP_GROUP"
    #else
    static let appGroup = "$APP_GROUP_IOS"
    #endif
}
SWIFT

# ── Entitlements: the App Group has to be spelled out in both ────────────────
cat > App/App.entitlements <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.application-groups</key>
    <array>
        <string>$APP_GROUP</string>
    </array>
</dict>
</plist>
PLIST

cat > Widget/Widget.entitlements <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <array>
        <string>$APP_GROUP</string>
    </array>
</dict>
</plist>
PLIST

# iOS: no sandbox/network keys (both are implicit), and the group.* form.
for f in iOS/iOSApp.entitlements iOS/iOSWidget.entitlements; do
    mkdir -p "$(dirname "$f")"
    cat > "$f" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.application-groups</key>
    <array>
        <string>$APP_GROUP_IOS</string>
    </array>
</dict>
</plist>
PLIST
done

# xcodegen expands ${VAR} in project.yml from the environment.
xcodegen generate >/dev/null
echo "    configured."
