#!/usr/bin/env bash
# Resolve the build identity and write the files that depend on it. Every build
# path runs this first (install.sh, build-release.sh, CI).
#
# Why generated: the Apple team id, bundle prefix and App Group name are yours,
# not the project's, and they have to agree in four places — project.yml, both
# .entitlements files, and Swift. Generating them from one source keeps them in
# step and keeps them out of the repo.
#
# Values come from, in order of precedence:
#   1. the environment
#   2. local-config/build.env   (gitignored — this machine's real values)
#   3. build.env.example        (committed placeholders, so a clone still builds)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

envval() { grep "^$1=" "$2" 2>/dev/null | head -1 | cut -d= -f2-; }

for key in BUNDLE_PREFIX APP_NAME DEVELOPMENT_TEAM; do
    if [ -z "${!key:-}" ]; then
        v="$(envval "$key" local-config/build.env)"
        [ -z "$v" ] && v="$(envval "$key" build.env.example)"
        export "$key=$v"
    fi
done
: "${BUNDLE_PREFIX:?missing — see build.env.example}"
: "${APP_NAME:?missing — see build.env.example}"
: "${DEVELOPMENT_TEAM:?missing — see build.env.example}"

# App Group naming differs by platform and both forms are mandatory:
#   macOS — must carry the Team ID prefix, or a sandboxed app can't open the
#           container it shares with its widget.
#   iOS   — must begin with "group.", and must NOT carry the team prefix.
# Getting this wrong fails at runtime (nil container URL), not at build time.
export APP_GROUP="${APP_GROUP:-$DEVELOPMENT_TEAM.group.$BUNDLE_PREFIX.$APP_NAME}"
export APP_GROUP_IOS="${APP_GROUP_IOS:-group.$BUNDLE_PREFIX.$APP_NAME}"
export BUNDLE_ID="${BUNDLE_ID:-$BUNDLE_PREFIX.$APP_NAME}"

echo "==> team $DEVELOPMENT_TEAM · bundle $BUNDLE_ID"
echo "    groups: macOS $APP_GROUP · iOS $APP_GROUP_IOS"

# ── Swift: one constant every target reads ───────────────────────────────────
cat > Shared/BuildConfig.generated.swift <<SWIFT
// Generated by scripts/configure.sh — do not edit, do not commit.
import Foundation

enum BuildConfig {
    #if os(macOS)
    static let appGroup = "$APP_GROUP"
    #else
    static let appGroup = "$APP_GROUP_IOS"
    #endif

    /// UTI for exported config files. Must match the UTExportedTypeDeclarations
    /// entry in the app's Info.plist, or UTType(exportedAs:) traps at runtime.
    static let configUTI = "$BUNDLE_ID.config"
    static let configFileExtension = "mywidgets"
}
SWIFT

# ── Entitlements ─────────────────────────────────────────────────────────────
# Written to entitlements/, which is NOT a source path — Xcode reads these via
# CODE_SIGN_ENTITLEMENTS only, so they must not be picked up as resources.
mkdir -p entitlements

sandbox_keys() {
    # macOS needs the sandbox and network client declared; on iOS both are
    # implicit and listing them is rejected.
    if [ "$1" = macOS ]; then
        printf '    <key>com.apple.security.app-sandbox</key>\n    <true/>\n    <key>com.apple.security.network.client</key>\n    <true/>\n'
    fi
}

write_entitlements() {
    local file="$1" platform="$2" group="$3" sandbox="$4"
    {
        echo '<?xml version="1.0" encoding="UTF-8"?>'
        echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
        echo '<plist version="1.0">'
        echo '<dict>'
        [ "$sandbox" = yes ] && sandbox_keys "$platform"
        echo '    <key>com.apple.security.application-groups</key>'
        echo '    <array>'
        echo "        <string>$group</string>"
        echo '    </array>'
        echo '</dict>'
        echo '</plist>'
    } > "$file"
}

# The app bundle itself is not sandboxed on macOS (it runs the `security` CLI);
# the widget extension is.
write_entitlements entitlements/macOS.entitlements       macOS "$APP_GROUP"     no
write_entitlements entitlements/macOSWidget.entitlements macOS "$APP_GROUP"     yes
write_entitlements entitlements/iOS.entitlements         iOS   "$APP_GROUP_IOS" no
write_entitlements entitlements/iOSWidget.entitlements   iOS   "$APP_GROUP_IOS" no

# xcodegen expands ${VAR} in project.yml from the environment.
xcodegen generate >/dev/null
echo "    configured."
